### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by eduardoacskimlinks** [tweak-extension/puppeteer-test-browser-ext#3]
<img width="955" alt="Screenshot 2023-02-17 at 08 12 14" src="https://user-images.githubusercontent.com/74052373/219589002-e68a6992-0a0b-4e57-98c6-932d6f2ee892.png">

**Comment by danielcaldas** [comment]
It seems you don't have chromium installed.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/11733994/219873839-eb285b50-d5cc-4c26-b166-a3a6af6fefb8.png">

**Comment by eduardoacskimlinks** [comment]
> It seems you don't have chromium installed.
> 
> <img alt="image" width="730" src="https://user-images.githubusercontent.com/11733994/219873839-eb285b50-d5cc-4c26-b166-a3a6af6fefb8.png">

Hi @danielcaldas, Thanks for your comment. 

I had set it up on my project without being required to install chromium on my laptop. 

Therefore, If the puppeteer package does not automatically install it, it's worth considering adding a pre-requisites section on the Readme. md or the [article](https://tweak-extension.com/blog/complete-guide-test-chrome-extension-puppeteer)

**Comment by danielcaldas** [comment]
That makes sense, done! Updated the README. Thanks!
